all:
	g++ --std=c++11 driver.cpp ../../shared/PiecewisePF.cpp ../../shared/ProbFunc.cpp ../../shared/FixedPF.cpp ../../shared/HistoPF.cpp ../../shared/UniformPF.cpp ../../shared/NormalPF.cpp ../../shared/ShiftPF.cpp -o test_probfunc
