all:
	g++ -g --std=c++11 merge.cpp ../../shared/PNG.cpp -lpng -o test_merge
	g++ -g --std=c++11 scramble.cpp ../../shared/PNG.cpp -lpng -o test_scramble
	g++ -g --std=c++11 make.cpp ../../shared/PNG.cpp -lpng -o test_make
