all:
	g++ -g --std=c++11 merge.cpp ../../shared/PNG.cpp -lpng -o merge
	g++ -g --std=c++11 scramble.cpp ../../shared/PNG.cpp -lpng -o scramble
	g++ -g --std=c++11 make.cpp ../../shared/PNG.cpp -lpng -o make
	g++ -g --std=c++11 recon.cpp ../../shared/PNG.cpp -lpng -o reconstruct
	g++ -g --std=c++11 reexpress.cpp ../../shared/PNG.cpp ../../shared/CSVFile.cpp ../../shared/Value.cpp -lpng -o reexpress
	g++ -g --std=c++11 randCSV.cpp -o randCSV
